# Generated by Django 3.1.6 on 2021-02-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210207_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='date',
        ),
    ]
