# Generated by Django 3.1.6 on 2021-02-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210207_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
